#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define DEVICE_ID              "stm32f767-bio-001"
#define UART_BAUDRATE          115200U
#define BIO_SAMPLE_PERIOD_MS   1000U
#define BIO_I2C_ADDR_7BIT      0x55U

/* Map these names to the GPIO pins generated by CubeMX.
 * If you use different pins, update these macros or your CubeMX labels.
 */
#define BIO_RST_GPIO_Port      GPIOB
#define BIO_RST_Pin            GPIO_PIN_0
#define BIO_MFIO_GPIO_Port     GPIOB
#define BIO_MFIO_Pin           GPIO_PIN_1

#endif /* APP_CONFIG_H */
