/*
 * STM32F767 biometric IoT demo main.c
 *
 * Use this file as a reference or merge the USER CODE blocks into the main.c
 * generated by STM32CubeMX. Peripheral init functions below are representative;
 * CubeMX may generate slightly different code for your board.
 */

#include "main.h"
#include "app_config.h"
#include "max32664.h"
#include "telemetry.h"
#include <string.h>

I2C_HandleTypeDef hi2c1;
UART_HandleTypeDef huart3;

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART3_UART_Init(void);
static void uart_print(const char *s);
static void Error_Handler(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART3_UART_Init();

    uart_print("\r\nSTM32F767 Biometric MQTT telemetry demo booting...\r\n");

    max32664_status_t st = max32664_begin(&hi2c1);
    if (st != MAX32664_OK) {
        uart_print("MAX32664 begin failed\r\n");
    } else {
        uart_print("MAX32664 detected\r\n");
    }

    st = max32664_config_bpm();
    if (st != MAX32664_OK) {
        uart_print("MAX32664 config failed\r\n");
    } else {
        uart_print("MAX32664 BPM algorithm configured\r\n");
    }

    uint32_t seq = 0;
    char line[256];

    while (1) {
        max32664_sample_t sample;
        st = max32664_read_bpm(&sample);

        int n;
        if (st == MAX32664_OK) {
            n = telemetry_format_json(line, sizeof(line), DEVICE_ID, seq++, &sample, HAL_GetTick());
        } else {
            n = telemetry_format_error_json(line, sizeof(line), DEVICE_ID, seq++, max32664_status_string(st), HAL_GetTick());
        }

        if (n > 0) {
            HAL_UART_Transmit(&huart3, (uint8_t *)line, (uint16_t)strlen(line), HAL_MAX_DELAY);
        }

        HAL_Delay(BIO_SAMPLE_PERIOD_MS);
    }
}

static void uart_print(const char *s)
{
    HAL_UART_Transmit(&huart3, (uint8_t *)s, (uint16_t)strlen(s), HAL_MAX_DELAY);
}

static void MX_I2C1_Init(void)
{
    hi2c1.Instance = I2C1;
    hi2c1.Init.Timing = 0x20404768; /* Typical 100 kHz timing; regenerate with CubeMX for your clock tree. */
    hi2c1.Init.OwnAddress1 = 0;
    hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2 = 0;
    hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) {
        Error_Handler();
    }

    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK) {
        Error_Handler();
    }

    if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK) {
        Error_Handler();
    }
}

static void MX_USART3_UART_Init(void)
{
    huart3.Instance = USART3;
    huart3.Init.BaudRate = UART_BAUDRATE;
    huart3.Init.WordLength = UART_WORDLENGTH_8B;
    huart3.Init.StopBits = UART_STOPBITS_1;
    huart3.Init.Parity = UART_PARITY_NONE;
    huart3.Init.Mode = UART_MODE_TX_RX;
    huart3.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart3.Init.OverSampling = UART_OVERSAMPLING_16;
    huart3.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart3.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    if (HAL_UART_Init(&huart3) != HAL_OK) {
        Error_Handler();
    }
}

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();

    HAL_GPIO_WritePin(BIO_RST_GPIO_Port, BIO_RST_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(BIO_MFIO_GPIO_Port, BIO_MFIO_Pin, GPIO_PIN_SET);

    GPIO_InitStruct.Pin = BIO_RST_Pin | BIO_MFIO_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

static void SystemClock_Config(void)
{
    /* Prefer the SystemClock_Config generated by CubeMX for your board.
     * This placeholder intentionally traps if used unchanged in a real project.
     */
}

static void Error_Handler(void)
{
    __disable_irq();
    while (1) { }
}
